### ISSUE TITLE
微信浏览器中 Input 的兼容性处理

### ISSUE THREAD

**Issue by toFrankie** [toFrankie/blog#158]
1. 在 iOS 上输入框默认样式会有内阴影，无法通过 `box-shadow: none` 去除，可通过以下方式处理。

```css
input {
  -webkit-appearance: none;
}
```

2. 在微信浏览器中部分 iOS 设备在输入框失焦时，页面无法正常回弹，可通过在 `input` 失焦事件加上：

```js
function blurHandler() {
  setTimeout(() => {
    const scrollHeight = document.documentElement.scrollTop || document.body.scrollTop || 0
    window.scrollTo(0, Math.max(scrollHeight - 1, 0))
  }, 0)
}
```
